platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
- name: source-code

run:
  path: "source-code/mvnw"
  args: ["--file", "source-code/pom.xml", "package"]
