platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine

inputs:
- name: source-code

run:
  path: "source-code/mvnw"
  args: ["--file", "source-code/pom.xml", "package"]

params:
  MAVEN_BASEDIR: source-code
