platform: linux

image_resource:
  type: docker-image
  source:
    repository: nitram509/alpine-oraclejdk8-maven-cmake-gcc
    tag: latest

inputs:
- name: source-code

run:
  path: "source-code/mvnw"
  args: ["--file", "source-code/pom.xml", "package"]

params:
  MAVEN_BASEDIR: source-code
